apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: library-deployment
  name: library-deployment
  namespace: uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: library-deployment
    spec:
      containers:
      - image: steve001steve/library:v8
        name: library
        imagePullPolicy: Always
        resources: {}
status: {}
