apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: library-deployment
  name: library-deployment
  namespace: uat
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: library-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
