
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: frontend-app
  namespace: vela-system  # Adjust if necessary
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: "steve001steve/library-frontend:latest"
        ports:
          - port: 80
            expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1

  policies:
    - name: target-pre-prod
      type: topology
      properties:
        clusters: ["local"]
        namespace: "pre-prod"

  workflow:
    steps:
      - name: deploy-to-pre-prod
        type: deploy
        properties:
          policies: ["target-pre-prod"]
