name: Docker Build and Push

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main
      - dev

# Define the job
jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      
      # Step 3: Build the Docker image for the frontend
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/library-frontend:latest ./frontend
      # Step 3: Build the Docker image for the Backend
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/library-backend:latest ./backend
            

      # Step 4: Push the Frontend Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/library-frontend:latest
      # Step 4: Push the backend Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/library-backend:latest